### PR TITLE
Add inital version of current BMO Chart

### PR DESCRIPTION
**Pull request by MaxRink**
This contributes our inital version of our BMO chart

### CODE REVIEW

**Comment by fmuyassarov** [comment]
@MaxRink Thank you! I will take a look later today.

**Comment by MaxRink** [comment]
@fmuyassarov ive also put up a PR for our ironic chart https://github.com/metal3-io/metal3-helm-chart/pull/16 as the new version drops deploying ironic and you need to do that differently.
It uses a different container than your ironic-image tho, we can publish the dockerfile too tho, its quite simple

**Comment by MaxRink** [comment]
and adding https://github.com/marketplace/actions/helm-chart-releaser might be a good idea, currently the charts are not really consumeable.
Its easy to do and i think you already use GH Pages in different repos, right?

**Pull request closed without merging**
